export default [
    {
        "countryGeonameId": 6252001,
        "countryName": "Afghanistan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "AF",
        "iso3Code": "AFG",
        "timeZone": "Asia/Kabul",
        "currency": "AFN ؋",
        "id": 1
    },
    {
        "countryGeonameId": 3164670,
        "countryName": "Åland",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "AX",
        "iso3Code": "FIN",
        "timeZone": "Europe/Mariehamn",
        "currency": "EUR €",
        "id": 2
    },
    {
        "countryGeonameId": 6290252,
        "countryName": "Albania",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "AL",
        "iso3Code": "ALB",
        "timeZone": "Europe/Tirane",
        "currency": "ALL L",
        "id": 3
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Algeria",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "DZ",
        "iso3Code": "DZA",
        "timeZone": "Africa/Algiers",
        "currency": "DZD د.ج",
        "id": 4
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "American Samoa",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "AS",
        "iso3Code": "ASM",
        "timeZone": "Pacific/Pago_Pago",
        "currency": "USD $",
        "id": 5
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Andorra",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "AD",
        "iso3Code": "AND",
        "timeZone": "Europe/Andorra",
        "currency": "EUR €",
        "id": 6
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Angola",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "AO",
        "iso3Code": "AGO",
        "timeZone": "Africa/Luanda",
        "currency": "AOA Kz",
        "id": 7
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Anguilla",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "AI",
        "iso3Code": "AIA",
        "timeZone": "America/Anguilla",
        "currency": "XCD $",
        "id": 8
    },
    {
        "countryGeonameId": 3017382,
        "countryName": "Antarctica",
        "continentName": "Antarctica",
        "localeCode": "en",
        "continentCode": "AN",
        "isoCode": "AQ",
        "iso3Code": "ATA",
        "timeZone": "Antarctica/Troll",
        "currency": "ANG ƒ",
        "id": 9
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Antigua and Barbuda",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "AG",
        "iso3Code": "ATG",
        "timeZone": "America/Antigua",
        "currency": "XCD $",
        "id": 10
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Argentina",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "AR",
        "iso3Code": "ARG",
        "timeZone": "America/Argentina/Ushuaia",
        "currency": "ARS $",
        "id": 11
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Armenia",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "AM",
        "iso3Code": "ARM",
        "timeZone": "Asia/Yerevan",
        "currency": "AMD ֏",
        "id": 12
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Aruba",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "AW",
        "iso3Code": "ABW",
        "timeZone": "America/Aruba",
        "currency": "AWG ƒ",
        "id": 13
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Australia",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "AU",
        "iso3Code": "AUS",
        "timeZone": "Australia/Sydney",
        "currency": "AUD $",
        "id": 14
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Austria",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "AT",
        "iso3Code": "AUT",
        "timeZone": "Europe/Vienna",
        "currency": "EUR €",
        "id": 15
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Azerbaijan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "AZ",
        "iso3Code": "AZE",
        "timeZone": "Asia/Baku",
        "currency": "AZN ₼",
        "id": 16
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bahamas",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "BS",
        "iso3Code": "BHS",
        "timeZone": "America/Nassau",
        "currency": "BSD $",
        "id": 17
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bahrain",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "BH",
        "iso3Code": "BHR",
        "timeZone": "Asia/Bahrain",
        "currency": "BHD دينار",
        "id": 18
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bangladesh",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "BD",
        "iso3Code": "BGD",
        "timeZone": "Asia/Dhaka",
        "currency": "BDT ৳",
        "id": 19
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Barbados",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "BB",
        "iso3Code": "BRB",
        "timeZone": "America/Barbados",
        "currency": "BBD $",
        "id": 20
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Belarus",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "BY",
        "iso3Code": "BLR",
        "timeZone": "Europe/Minsk",
        "currency": "BYN Br",
        "id": 21
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Belgium",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "BE",
        "iso3Code": "BEL",
        "timeZone": "Europe/Brussels",
        "currency": "EUR €",
        "id": 22
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Belize",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "BZ",
        "iso3Code": "BLZ",
        "timeZone": "America/Belize",
        "currency": "BZD $",
        "id": 23
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Benin",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "BJ",
        "iso3Code": "BEN",
        "timeZone": "Africa/Porto-Novo",
        "currency": "CFA Fr",
        "id": 24
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bermuda",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "BM",
        "iso3Code": "BMU",
        "timeZone": "Atlantic/Bermuda",
        "currency": "BMD $",
        "id": 25
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bhutan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "BT",
        "iso3Code": "BTN",
        "timeZone": "Asia/Thimphu",
        "currency": "BTN Nu.",
        "id": 26
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bolivia",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "BO",
        "iso3Code": "BOL",
        "timeZone": "America/La_Paz",
        "currency": "BOB Bs.",
        "id": 27
    },
    {
        "countryGeonameId": 7909807,
        "countryName": "Bonaire, Sint Eustatius, and Saba",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "BQ",
        "iso3Code": "BES",
        "timeZone": "America/Kralendijk",
        "currency": "$",
        "id": 28
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bosnia and Herzegovina",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "BA",
        "iso3Code": "BIH",
        "timeZone": "Europe/Sarajevo",
        "currency": "BAM KM",
        "id": 29
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Botswana",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "BW",
        "iso3Code": "BWA",
        "timeZone": "Africa/Gaborone",
        "currency": "BWP P",
        "id": 30
    },
    {
        "countryGeonameId": 3077311,
        "countryName": "Bouvet Island",
        "continentName": "Antarctica",
        "localeCode": "en",
        "continentCode": "AN",
        "isoCode": "BV",
        "iso3Code": "BVT",
        "timeZone": "Europe/Oslo",
        "currency": "N/A",
        "id": 31
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Brazil",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "BR",
        "iso3Code": "BRA",
        "timeZone": "America/Sao_Paulo",
        "currency": "BRL R$",
        "id": 32
    },
    {
        "countryGeonameId": 6251999,
        "countryName": "British Indian Ocean Territory",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "IO",
        "iso3Code": "IOT",
        "timeZone": "Indian/Chagos",
        "currency": "USD $",
        "id": 33
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "British Virgin Islands",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "VG",
        "iso3Code": "VGB",
        "timeZone": "America/Tortola",
        "currency": "USD $",
        "id": 34
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Brunei",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "BN",
        "iso3Code": "BRN",
        "timeZone": "Asia/Brunei",
        "currency": "BND $",
        "id": 35
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Bulgaria",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "BG",
        "iso3Code": "BGR",
        "timeZone": "Europe/Sofia",
        "currency": "BGN лв",
        "id": 36
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Burkina Faso",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "BF",
        "iso3Code": "BFA",
        "timeZone": "Africa/Ouagadougou",
        "currency": "CFA Fr",
        "id": 37
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Burundi",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "BI",
        "iso3Code": "BDI",
        "timeZone": "Africa/Bujumbura",
        "currency": "BIF Fr",
        "id": 38
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Cambodia",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "KH",
        "iso3Code": "KHM",
        "timeZone": "Asia/Phnom_Penh",
        "currency": "KHR ៛",
        "id": 39
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Cameroon",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "CM",
        "iso3Code": "CMR",
        "timeZone": "Africa/Douala",
        "currency": "CFA Fr",
        "id": 40
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Canada",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "CA",
        "iso3Code": "CAN",
        "timeZone": "America/Yellowknife",
        "currency": "CAD $",
        "id": 41
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Cayman Islands",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "KY",
        "iso3Code": "CYM",
        "timeZone": "America/Cayman",
        "currency": "KYD $",
        "id": 42
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Central African Republic",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "CF",
        "iso3Code": "CAF",
        "timeZone": "Africa/Bangui",
        "currency": "CFA Fr",
        "id": 43
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Chad",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "TD",
        "iso3Code": "TCD",
        "timeZone": "Africa/Ndjamena",
        "currency": "CFA Fr",
        "id": 44
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Chile",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "CL",
        "iso3Code": "CHL",
        "timeZone": "America/Santiago",
        "currency": "CLP $",
        "id": 45
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "China",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "CN",
        "iso3Code": "CHN",
        "timeZone": "Asia/Urumqi",
        "currency": "CNY ¥",
        "id": 46
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Christmas Island",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "CX",
        "iso3Code": "CXR",
        "timeZone": "Indian/Christmas",
        "currency": "AUD $",
        "id": 47
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Cocos [Keeling] Islands",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "CC",
        "iso3Code": "CCK",
        "timeZone": "Indian/Cocos",
        "currency": "USD $",
        "id": 48
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Colombia",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "CO",
        "iso3Code": "COL",
        "timeZone": "America/Bogota",
        "currency": "COP $",
        "id": 49
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Comoros",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "KM",
        "iso3Code": "COM",
        "timeZone": "Indian/Comoro",
        "currency": "KMF Fr",
        "id": 50
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Congo",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "CD",
        "iso3Code": "COG",
        "timeZone": "Africa/Lubumbashi",
        "currency": "CDF Fr",
        "id": 51
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Cook Islands",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "CK",
        "iso3Code": "COK",
        "timeZone": "Pacific/Rarotonga",
        "currency": "NZD $",
        "id": 52
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Costa Rica",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "CR",
        "iso3Code": "CRI",
        "timeZone": "America/Costa_Rica",
        "currency": "CRC ₡",
        "id": 53
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Croatia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "HR",
        "iso3Code": "HRV",
        "timeZone": "Europe/Zagreb",
        "currency": "HRK kn",
        "id": 54
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Cuba",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "CU",
        "iso3Code": "CUB",
        "timeZone": "America/Havana",
        "currency": "CUC $",
        "id": 55
    },
    {
        "countryGeonameId": 7626844,
        "countryName": "Curaçao",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "CW",
        "iso3Code": "CUW",
        "timeZone": "America/Curacao",
        "currency": "SDG £",
        "id": 56
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Cyprus",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "CY",
        "iso3Code": "CYP",
        "timeZone": "Asia/Nicosia",
        "currency": "EUR €",
        "id": 57
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Czechia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "CZ",
        "iso3Code": "CZE",
        "timeZone": "Europe/Prague",
        "currency": "CZK Kč",
        "id": 58
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Denmark",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "DK",
        "iso3Code": "DNK",
        "timeZone": "Europe/Copenhagen",
        "currency": "DKK kr",
        "id": 59
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Djibouti",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "DJ",
        "iso3Code": "DJI",
        "timeZone": "Africa/Djibouti",
        "currency": "DJF Fr",
        "id": 60
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Dominica",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "DM",
        "iso3Code": "DMA",
        "timeZone": "America/Dominica",
        "currency": "XCD $",
        "id": 61
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Dominican Republic",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "DO",
        "iso3Code": "DOM",
        "timeZone": "America/Santo_Domingo",
        "currency": "DOP $",
        "id": 62
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Ecuador",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "EC",
        "iso3Code": "ECU",
        "timeZone": "Pacific/Galapagos",
        "currency": "USD $",
        "id": 63
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Egypt",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "EG",
        "iso3Code": "EGY",
        "timeZone": "Africa/Cairo",
        "currency": "EGP E£",
        "id": 64
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "El Salvador",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "SV",
        "iso3Code": "SLV",
        "timeZone": "America/El_Salvador",
        "currency": "SVC $",
        "id": 65
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Equatorial Guinea",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "GQ",
        "iso3Code": "GNQ",
        "timeZone": "Africa/Malabo",
        "currency": "CFA Fr",
        "id": 66
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Eritrea",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "ER",
        "iso3Code": "ERI",
        "timeZone": "Africa/Asmara",
        "currency": "ERN Nfk",
        "id": 67
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Estonia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "EE",
        "iso3Code": "EST",
        "timeZone": "Europe/Tallinn",
        "currency": "EUR €",
        "id": 68
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Ethiopia",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "ET",
        "iso3Code": "ETH",
        "timeZone": "Africa/Addis_Ababa",
        "currency": "ETB Br",
        "id": 69
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Falkland Islands",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "FK",
        "iso3Code": "FLK",
        "timeZone": "Atlantic/Stanley",
        "currency": "FKP £",
        "id": 70
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Faroe Islands",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "FO",
        "iso3Code": "FRO",
        "timeZone": "Atlantic/Faroe",
        "currency": "DKK kr",
        "id": 71
    },
    {
        "countryGeonameId": 2081918,
        "countryName": "Federated States of Micronesia",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "FM",
        "iso3Code": "FSM",
        "timeZone": "Pacific/Pohnpei",
        "currency": "USD $",
        "id": 72
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Fiji",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "FJ",
        "iso3Code": "FJI",
        "timeZone": "Pacific/Fiji",
        "currency": "FJD $",
        "id": 73
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Finland",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "FI",
        "iso3Code": "FIN",
        "timeZone": "Europe/Helsinki",
        "currency": "EUR €",
        "id": 74
    },
    {
        "countryGeonameId": 6290252,
        "countryName": "France",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "FR",
        "iso3Code": "FRA",
        "timeZone": "Europe/Paris",
        "currency": "EUR €",
        "id": 75
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "French Guiana",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "GF",
        "iso3Code": "GUF",
        "timeZone": "America/Cayenne",
        "currency": "EUR €",
        "id": 76
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "French Polynesia",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "PF",
        "iso3Code": "PYF",
        "timeZone": "Pacific/Tahiti",
        "currency": "CFP Fr",
        "id": 77
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "French Southern Territories",
        "continentName": "Antarctica",
        "localeCode": "en",
        "continentCode": "AN",
        "isoCode": "TF",
        "iso3Code": "ATF",
        "timeZone": "Indian/Kerguelen",
        "currency": "EUR €",
        "id": 78
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Gabon",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "GA",
        "iso3Code": "GAB",
        "timeZone": "Africa/Libreville",
        "currency": "CFA Fr",
        "id": 79
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Gambia",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "GM",
        "iso3Code": "GMB",
        "timeZone": "Africa/Banjul",
        "currency": "GMD D",
        "id": 80
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Georgia",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "GE",
        "iso3Code": "GEO",
        "timeZone": "Asia/Tbilisi",
        "currency": "GEL ₾",
        "id": 81
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Germany",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "DE",
        "iso3Code": "DEU",
        "timeZone": "Europe/Berlin",
        "currency": "EUR €",
        "id": 82
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Ghana",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "GH",
        "iso3Code": "GHA",
        "timeZone": "Africa/Accra",
        "currency": "GHS ₵",
        "id": 83
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Gibraltar",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "GI",
        "iso3Code": "GIB",
        "timeZone": "Europe/Gibraltar",
        "currency": "GBP £",
        "id": 84
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Greece",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "GR",
        "iso3Code": "GRC",
        "timeZone": "Europe/Athens",
        "currency": "EUR €",
        "id": 85
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Greenland",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "GL",
        "iso3Code": "GRL",
        "timeZone": "America/Thule",
        "currency": "DKK Kr",
        "id": 86
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Grenada",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "GD",
        "iso3Code": "GRD",
        "timeZone": "America/Grenada",
        "currency": "XCD $",
        "id": 87
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Guadeloupe",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "GP",
        "iso3Code": "GLP",
        "timeZone": "America/Guadeloupe",
        "currency": "EUR €",
        "id": 88
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Guam",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "GU",
        "iso3Code": "GUM",
        "timeZone": "Pacific/Guam",
        "currency": "USD $",
        "id": 89
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Guatemala",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "GT",
        "iso3Code": "GTM",
        "timeZone": "America/Guatemala",
        "currency": "GTQ Q",
        "id": 90
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Guernsey",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "GG",
        "iso3Code": "GGY",
        "timeZone": "Europe/Guernsey",
        "currency": "GGP £",
        "id": 91
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Guinea",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "GN",
        "iso3Code": "GIN",
        "timeZone": "Africa/Conakry",
        "currency": "CFA Fr",
        "id": 92
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Guinea-Bissau",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "GW",
        "iso3Code": "GNB",
        "timeZone": "Africa/Bissau",
        "currency": "CFA Fr",
        "id": 93
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Guyana",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "GY",
        "iso3Code": "GUY",
        "timeZone": "America/Guyana",
        "currency": "GYD $",
        "id": 94
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Haiti",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "HT",
        "iso3Code": "HTI",
        "timeZone": "America/Port-au-Prince",
        "currency": "HTG G",
        "id": 95
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Heard Island and McDonald Islands",
        "continentName": "Antarctica",
        "localeCode": "en",
        "continentCode": "AN",
        "isoCode": "HM",
        "iso3Code": "HMD",
        "timeZone": "Indian/Kerguelen",
        "currency": "USD $",
        "id": 96
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Honduras",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "HN",
        "iso3Code": "HND",
        "timeZone": "America/Tegucigalpa",
        "currency": "HNL L",
        "id": 97
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Hong Kong",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "HK",
        "iso3Code": "HKG",
        "timeZone": "Asia/Hong_Kong",
        "currency": "HKD $",
        "id": 98
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Hungary",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "HU",
        "iso3Code": "HUN",
        "timeZone": "Europe/Budapest",
        "currency": "MKD Ft",
        "id": 99
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Iceland",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "IS",
        "iso3Code": "ISL",
        "timeZone": "Atlantic/Reykjavik",
        "currency": "ISK Kr",
        "id": 100
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "India",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "IN",
        "iso3Code": "IND",
        "timeZone": "Asia/Kolkata",
        "currency": "INR ₹",
        "id": 101
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Indonesia",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "ID",
        "iso3Code": "IDN",
        "timeZone": "Asia/Pontianak",
        "currency": "IDR Rp",
        "id": 102
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Iran",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "IR",
        "iso3Code": "IRN",
        "timeZone": "Asia/Tehran",
        "currency": "IRR ﷼ ",
        "id": 103
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Iraq",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "IQ",
        "iso3Code": "IRQ",
        "timeZone": "Asia/Baghdad",
        "currency": " IQD ع.د",
        "id": 104
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Ireland",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "IE",
        "iso3Code": "IRL",
        "timeZone": "Europe/Dublin",
        "currency": "EUR €",
        "id": 105
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Isle of Man",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "IM",
        "iso3Code": "IMN",
        "timeZone": "Europe/Isle_of_Man",
        "currency": "IMP £",
        "id": 106
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Israel",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "IL",
        "iso3Code": "ISR",
        "timeZone": "Asia/Jerusalem",
        "currency": "ILS ₪",
        "id": 107
    },
    {
        "countryGeonameId": 7626836,
        "countryName": "Italy",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "IT",
        "iso3Code": "ITA",
        "timeZone": "Europe/Rome",
        "currency": "EUR €",
        "id": 108
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Ivory Coast",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "CI",
        "iso3Code": "CIV",
        "timeZone": "Africa/Abidjan",
        "currency": "CFA Fr",
        "id": 109
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Jamaica",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "JM",
        "iso3Code": "JAM",
        "timeZone": "America/Jamaica",
        "currency": "JMD $",
        "id": 110
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Japan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "JP",
        "iso3Code": "JPN",
        "timeZone": "Asia/Tokyo",
        "currency": "JPY ¥",
        "id": 111
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Jersey",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "JE",
        "iso3Code": "JEY",
        "timeZone": "Europe/Jersey",
        "currency": "JEP £",
        "id": 112
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Kazakhstan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "KZ",
        "iso3Code": "KAZ",
        "timeZone": "Asia/Qyzylorda",
        "currency": "KZT ₸",
        "id": 113
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Kenya",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "KE",
        "iso3Code": "KEN",
        "timeZone": "Africa/Nairobi",
        "currency": "KES Sh",
        "id": 114
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Kiribati",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "KI",
        "iso3Code": "KIR",
        "timeZone": "Pacific/Tarawa",
        "currency": "AUD $",
        "id": 115
    },
    {
        "countryGeonameId": 6290252,
        "countryName": "Kosovo",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "XK",
        "iso3Code": "UNK",
        "timeZone": "Europe/Belgrade",
        "currency": "EUR €",
        "id": 116
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Kuwait",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "KW",
        "iso3Code": "KWT",
        "timeZone": "Asia/Kuwait",
        "currency": "KWD د.ك",
        "id": 117
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Kyrgyzstan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "KG",
        "iso3Code": "KGZ",
        "timeZone": "Asia/Bishkek",
        "currency": "KGS c",
        "id": 118
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Laos",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "LA",
        "iso3Code": "LAO",
        "timeZone": "Asia/Vientiane",
        "currency": "LAK ₭",
        "id": 119
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Latvia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "LV",
        "iso3Code": "LVA",
        "timeZone": "Europe/Riga",
        "currency": "EUR €",
        "id": 120
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Lebanon",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "LB",
        "iso3Code": "LBN",
        "timeZone": "Asia/Beirut",
        "currency": " LBP ل.ل",
        "id": 121
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Lesotho",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "LS",
        "iso3Code": "LSO",
        "timeZone": "Africa/Maseru",
        "currency": "LSL L",
        "id": 122
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Liberia",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "LR",
        "iso3Code": "LBR",
        "timeZone": "Africa/Monrovia",
        "currency": "LRD $",
        "id": 123
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Libya",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "LY",
        "iso3Code": "LBY",
        "timeZone": "Africa/Tripoli",
        "currency": "LYD ل.د",
        "id": 124
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Liechtenstein",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "LI",
        "iso3Code": "LIE",
        "timeZone": "Europe/Vaduz",
        "currency": "CHF Fr",
        "id": 125
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Luxembourg",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "LU",
        "iso3Code": "LUX",
        "timeZone": "Europe/Luxembourg",
        "currency": "EUR €",
        "id": 126
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Macao",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "MO",
        "iso3Code": "MAC",
        "timeZone": "Asia/Shanghai",
        "currency": "MOP P",
        "id": 127
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Madagascar",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "MG",
        "iso3Code": "MDG",
        "timeZone": "Indian/Antananarivo",
        "currency": "MGA Ar",
        "id": 128
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Malawi",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "MW",
        "iso3Code": "MWI",
        "timeZone": "Africa/Blantyre",
        "currency": "MWK MK",
        "id": 129
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Malaysia",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "MY",
        "iso3Code": "MYS",
        "timeZone": "Asia/Kuching",
        "currency": "MYR RM",
        "id": 130
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Maldives",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "MV",
        "iso3Code": "MDV",
        "timeZone": "Indian/Maldives",
        "currency": "MVR .ރ",
        "id": 131
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Mali",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "ML",
        "iso3Code": "MLI",
        "timeZone": "Africa/Bamako",
        "currency": "CFA Fr",
        "id": 132
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Malta",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "MT",
        "iso3Code": "MLT",
        "timeZone": "Europe/Malta",
        "currency": "EUR €",
        "id": 133
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Marshall Islands",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "MH",
        "iso3Code": "MHL",
        "timeZone": "Pacific/Majuro",
        "currency": "USD $",
        "id": 134
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Martinique",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "MQ",
        "iso3Code": "MTQ",
        "timeZone": "America/Martinique",
        "currency": "EUR €",
        "id": 135
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Mauritania",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "MR",
        "iso3Code": "MRT",
        "timeZone": "Africa/Nouakchott",
        "currency": "MRU UM",
        "id": 136
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Mauritius",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "MU",
        "iso3Code": "MUS",
        "timeZone": "Indian/Mauritius",
        "currency": "MUR ₨",
        "id": 137
    },
    {
        "countryGeonameId": 3164670,
        "countryName": "Mayotte",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "YT",
        "iso3Code": "MYT",
        "timeZone": "Indian/Mayotte",
        "currency": "EUR €",
        "id": 138
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Mexico",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "MX",
        "iso3Code": "MEX",
        "timeZone": "America/Tijuana",
        "currency": "MXN $",
        "id": 139
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Monaco",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "MC",
        "iso3Code": "MCO",
        "timeZone": "Europe/Monaco",
        "currency": "EUR €",
        "id": 140
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Mongolia",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "MN",
        "iso3Code": "MNG",
        "timeZone": "Asia/Ulaanbaatar",
        "currency": "MNT ₮",
        "id": 141
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Montenegro",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "ME",
        "iso3Code": "MNE",
        "timeZone": "Europe/Podgorica",
        "currency": "EUR €",
        "id": 142
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Montserrat",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "MS",
        "iso3Code": "MSR",
        "timeZone": "America/Montserrat",
        "currency": "XCD $",
        "id": 143
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Morocco",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "MA",
        "iso3Code": "MAR",
        "timeZone": "Africa/El_Aaiun",
        "currency": "MAD د.م. ",
        "id": 144
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Mozambique",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "MZ",
        "iso3Code": "MOZ",
        "timeZone": "Africa/Maputo",
        "currency": "MZN MT",
        "id": 145
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Myanmar",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "MM",
        "iso3Code": "MMR",
        "timeZone": "Asia/Yangon",
        "currency": "MMK Ks",
        "id": 146
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Namibia",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "NA",
        "iso3Code": "NAM",
        "timeZone": "Africa/Windhoek",
        "currency": "NAD $",
        "id": 147
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Nauru",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "NR",
        "iso3Code": "NRU",
        "timeZone": "Pacific/Nauru",
        "currency": "AUD $",
        "id": 148
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Nepal",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "NP",
        "iso3Code": "NPL",
        "timeZone": "Asia/Kathmandu",
        "currency": "NPR ₨",
        "id": 149
    },
    {
        "countryGeonameId": 6254930,
        "countryName": "Netherlands",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "NL",
        "iso3Code": "NLD",
        "timeZone": "Europe/Amsterdam",
        "currency": "EUR €",
        "id": 150
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "New Caledonia",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "NC",
        "iso3Code": "NCL",
        "timeZone": "Pacific/Noumea",
        "currency": "CFP Fr",
        "id": 151
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "New Zealand",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "NZ",
        "iso3Code": "NZL",
        "timeZone": "Pacific/Chatham",
        "currency": "NZD $",
        "id": 152
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Nicaragua",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "NI",
        "iso3Code": "NIC",
        "timeZone": "America/Managua",
        "currency": "NIO C$",
        "id": 153
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Niger",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "NE",
        "iso3Code": "NER",
        "timeZone": "Africa/Niamey",
        "currency": "CFA Fr",
        "id": 154
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Nigeria",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "NG",
        "iso3Code": "NGA",
        "timeZone": "Africa/Lagos",
        "currency": "NGN ₦",
        "id": 155
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Niue",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "NU",
        "iso3Code": "NIU",
        "timeZone": "Pacific/Niue",
        "currency": "NZD $",
        "id": 156
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Norfolk Island",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "NF",
        "iso3Code": "NFK",
        "timeZone": "Pacific/Norfolk",
        "currency": "AUD $",
        "id": 157
    },
    {
        "countryGeonameId": 1873107,
        "countryName": "North Korea",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "KP",
        "iso3Code": "PRK",
        "timeZone": "Asia/Pyongyang",
        "currency": "KPW ₩",
        "id": 158
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Northern Mariana Islands",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "MP",
        "iso3Code": "MNP",
        "timeZone": "Pacific/Saipan",
        "currency": "USD $",
        "id": 159
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Norway",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "NO",
        "iso3Code": "NOR",
        "timeZone": "Europe/Oslo",
        "currency": "NOK kr",
        "id": 160
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Oman",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "OM",
        "iso3Code": "OMN",
        "timeZone": "Asia/Muscat",
        "currency": "OMR ر.ع.",
        "id": 161
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Pakistan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "PK",
        "iso3Code": "PAK",
        "timeZone": "Asia/Karachi",
        "currency": "PKR ₨",
        "id": 162
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Palau",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "PW",
        "iso3Code": "PLW",
        "timeZone": "Pacific/Palau",
        "currency": "USD $",
        "id": 163
    },
    {
        "countryGeonameId": 6254930,
        "countryName": "Palestine",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "PS",
        "iso3Code": "PSE",
        "timeZone": "Asia/Jerusalem",
        "currency": "ILS ₪",
        "id": 164
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Panama",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "PA",
        "iso3Code": "PAN",
        "timeZone": "America/Panama",
        "currency": "PAB $",
        "id": 165
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Papua New Guinea",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "PG",
        "iso3Code": "PNG",
        "timeZone": "Pacific/Port_Moresby",
        "currency": "PGK K",
        "id": 166
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Paraguay",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "PY",
        "iso3Code": "PRY",
        "timeZone": "America/Asuncion",
        "currency": "PYG ₲",
        "id": 167
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Peru",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "PE",
        "iso3Code": "PER",
        "timeZone": "America/Lima",
        "currency": "PEN S/",
        "id": 168
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Philippines",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "PH",
        "iso3Code": "PHL",
        "timeZone": "Asia/Manila",
        "currency": "PHP ₱",
        "id": 169
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Pitcairn Islands",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "PN",
        "iso3Code": "PCN",
        "timeZone": "Pacific/Pitcairn",
        "currency": "NZD $",
        "id": 170
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Poland",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "PL",
        "iso3Code": "POL",
        "timeZone": "Europe/Warsaw",
        "currency": "PLN zł",
        "id": 171
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Portugal",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "PT",
        "iso3Code": "PRT",
        "timeZone": "Europe/Madrid",
        "currency": "EUR €",
        "id": 172
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Puerto Rico",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "PR",
        "iso3Code": "PRI",
        "timeZone": "America/Puerto_Rico",
        "currency": "USD $",
        "id": 173
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Qatar",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "QA",
        "iso3Code": "QAT",
        "timeZone": "Asia/Qatar",
        "currency": "QAR ر.ق ",
        "id": 174
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Republic of the Congo",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "CG",
        "iso3Code": "COD",
        "timeZone": "Africa/Brazzaville",
        "currency": "CDF Fr",
        "id": 175
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Réunion",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "RE",
        "iso3Code": "REU",
        "timeZone": "Indian/Reunion",
        "currency": "EUR €",
        "id": 176
    },
    {
        "countryGeonameId": 6290252,
        "countryName": "Romania",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "RO",
        "iso3Code": "ROU",
        "timeZone": "Europe/Bucharest",
        "currency": "RON lei",
        "id": 177
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Russia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "RU",
        "iso3Code": "RUS",
        "timeZone": "Europe/Volgograd",
        "currency": "RUB ₽",
        "id": 178
    },
    {
        "countryGeonameId": 7909807,
        "countryName": "Rwanda",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "RW",
        "iso3Code": "RWA",
        "timeZone": "Africa/Kigali",
        "currency": "RWF Fr",
        "id": 179
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Saint Barthélemy",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "BL",
        "iso3Code": "BLM",
        "timeZone": "America/St_Barthelemy",
        "currency": "EUR €",
        "id": 180
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Saint Helena",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "SH",
        "iso3Code": "SHN",
        "timeZone": "Atlantic/St_Helena",
        "currency": "SHP £",
        "id": 181
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Saint Lucia",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "LC",
        "iso3Code": "LCA",
        "timeZone": "America/St_Lucia",
        "currency": "XCD $",
        "id": 182
    },
    {
        "countryGeonameId": 7609695,
        "countryName": "Saint Martin",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "MF",
        "iso3Code": "MAF",
        "timeZone": "America/Marigot",
        "currency": "EUR €",
        "id": 183
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Saint Pierre and Miquelon",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "PM",
        "iso3Code": "SPM",
        "timeZone": "America/Miquelon",
        "currency": "EUR €",
        "id": 184
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Saint Vincent and the Grenadines",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "VC",
        "iso3Code": "VCT",
        "timeZone": "America/St_Vincent",
        "currency": "XCD $",
        "id": 185
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Samoa",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "WS",
        "iso3Code": "WSM",
        "timeZone": "Pacific/Apia",
        "currency": "WST T",
        "id": 186
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "San Marino",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "SM",
        "iso3Code": "SMR",
        "timeZone": "Europe/San_Marino",
        "currency": "EUR €",
        "id": 187
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "São Tomé and Príncipe",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "ST",
        "iso3Code": "STP",
        "timeZone": "Africa/Sao_Tome",
        "currency": "STN Db",
        "id": 188
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Saudi Arabia",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "SA",
        "iso3Code": "SAU",
        "timeZone": "Asia/Riyadh",
        "currency": "SAR ر.س ",
        "id": 189
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Senegal",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "SN",
        "iso3Code": "SEN",
        "timeZone": "Africa/Dakar",
        "currency": "CFA Fr",
        "id": 190
    },
    {
        "countryGeonameId": 6290252,
        "countryName": "Serbia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "RS",
        "iso3Code": "SRB",
        "timeZone": "Europe/Zagreb",
        "currency": "ANG ƒ",
        "id": 191
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Seychelles",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "SC",
        "iso3Code": "SYC",
        "timeZone": "Indian/Mahe",
        "currency": "SCR ₨",
        "id": 192
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Sierra Leone",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "SL",
        "iso3Code": "SLE",
        "timeZone": "Africa/Freetown",
        "currency": "SLL Le",
        "id": 193
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Singapore",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "SG",
        "iso3Code": "SGP",
        "timeZone": "Asia/Singapore",
        "currency": "SGD $",
        "id": 194
    },
    {
        "countryGeonameId": 7609695,
        "countryName": "Sint Maarten",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "SX",
        "iso3Code": "SXM",
        "timeZone": "America/Lower_Princes",
        "currency": "USD $",
        "id": 195
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Slovakia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "SK",
        "iso3Code": "SVK",
        "timeZone": "Europe/Bratislava",
        "currency": "EUR €",
        "id": 196
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Slovenia",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "SI",
        "iso3Code": "SVN",
        "timeZone": "Europe/Ljubljana",
        "currency": "EUR €",
        "id": 197
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Solomon Islands",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "SB",
        "iso3Code": "SLB",
        "timeZone": "Pacific/Guadalcanal",
        "currency": "SBD $",
        "id": 198
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Somalia",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "SO",
        "iso3Code": "SOM",
        "timeZone": "Africa/Mogadishu",
        "currency": "SOS Sh",
        "id": 199
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "South Africa",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "ZA",
        "iso3Code": "ZAF",
        "timeZone": "Africa/Johannesburg",
        "currency": "ZAR R",
        "id": 200
    },
    {
        "countryGeonameId": 7909807,
        "countryName": "South Georgia and the South Sandwich Islands",
        "continentName": "Antarctica",
        "localeCode": "en",
        "continentCode": "AN",
        "isoCode": "GS",
        "iso3Code": "SGS",
        "timeZone": "Atlantic/South_Georgia",
        "currency": "GBP £",
        "id": 201
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "South Korea",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "KR",
        "iso3Code": "KOR",
        "timeZone": "Asia/Seoul",
        "currency": "KRW ₩",
        "id": 202
    },
    {
        "countryGeonameId": 7909807,
        "countryName": "South Sudan",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "SS",
        "iso3Code": "SSD",
        "timeZone": "Africa/Juba",
        "currency": "£",
        "id": 203
    },
    {
        "countryGeonameId": 6290252,
        "countryName": "Spain",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "ES",
        "iso3Code": "ESP",
        "timeZone": "Europe/Madrid",
        "currency": "EUR €",
        "id": 204
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Sri Lanka",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "LK",
        "iso3Code": "LKA",
        "timeZone": "Asia/Colombo",
        "currency": "LKR Rs",
        "id": 205
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "St Kitts and Nevis",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "KN",
        "iso3Code": "KNA",
        "timeZone": "America/St_Kitts",
        "currency": "XCD $",
        "id": 206
    },
    {
        "countryGeonameId": 7909807,
        "countryName": "Sudan",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "SD",
        "iso3Code": "SDN",
        "timeZone": "Africa/Khartoum",
        "currency": " SDG ج.س.",
        "id": 207
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Suriname",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "SR",
        "iso3Code": "SUR",
        "timeZone": "America/Paramaribo",
        "currency": "SRD $",
        "id": 208
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Svalbard and Jan Mayen",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "SJ",
        "iso3Code": "SJM",
        "timeZone": "Arctic/Longyearbyen",
        "currency": "NOK Kr",
        "id": 209
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Sweden",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "SE",
        "iso3Code": "SWE",
        "timeZone": "Europe/Stockholm",
        "currency": "SEK Kr",
        "id": 210
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Switzerland",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "CH",
        "iso3Code": "CHE",
        "timeZone": "Europe/Zurich",
        "currency": "CHF Fr",
        "id": 211
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Syria",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "SY",
        "iso3Code": "SYR",
        "timeZone": "Asia/Damascus",
        "currency": "SYP £S",
        "id": 212
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Taiwan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "TW",
        "iso3Code": "TWN",
        "timeZone": "Asia/Taipei",
        "currency": "TWD $",
        "id": 213
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Tajikistan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "TJ",
        "iso3Code": "TJK",
        "timeZone": "Asia/Dushanbe",
        "currency": "TJS SM",
        "id": 214
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Tanzania",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "TZ",
        "iso3Code": "TZA",
        "timeZone": "Africa/Dar_es_Salaam",
        "currency": "TZS Sh",
        "id": 215
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Thailand",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "TH",
        "iso3Code": "THA",
        "timeZone": "Asia/Bangkok",
        "currency": "THB ฿",
        "id": 216
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Togo",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "TG",
        "iso3Code": "TGO",
        "timeZone": "Africa/Lome",
        "currency": "CFA Fr",
        "id": 217
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Tokelau",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "TK",
        "iso3Code": "TKL",
        "timeZone": "Pacific/Fakaofo",
        "currency": "NZD $",
        "id": 218
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Tonga",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "TO",
        "iso3Code": "TON",
        "timeZone": "Pacific/Tongatapu",
        "currency": "TOP T$",
        "id": 219
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Trinidad and Tobago",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "TT",
        "iso3Code": "TTO",
        "timeZone": "America/Port_of_Spain",
        "currency": "TTD $",
        "id": 220
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Tunisia",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "TN",
        "iso3Code": "TUN",
        "timeZone": "Africa/Tunis",
        "currency": "TND ملّيم",
        "id": 221
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Turkey",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "TR",
        "iso3Code": "TUR",
        "timeZone": "Europe/Istanbul",
        "currency": "TRY ₺",
        "id": 222
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Turkmenistan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "TM",
        "iso3Code": "TKM",
        "timeZone": "Asia/Ashgabat",
        "currency": "TMT m",
        "id": 223
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Turks and Caicos Islands",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "TC",
        "iso3Code": "TCA",
        "timeZone": "America/Grand_Turk",
        "currency": "USD $",
        "id": 224
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Tuvalu",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "TV",
        "iso3Code": "TUV",
        "timeZone": "Pacific/Funafuti",
        "currency": "TVD $",
        "id": 225
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "U.S. Minor Outlying Islands",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "UM",
        "iso3Code": "UMI",
        "timeZone": "Pacific/Wake",
        "currency": "USD $",
        "id": 226
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "U.S. Virgin Islands",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "VI",
        "iso3Code": "VIR",
        "timeZone": "America/St_Thomas",
        "currency": "USD $",
        "id": 227
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Uganda",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "UG",
        "iso3Code": "UGA",
        "timeZone": "Africa/Kampala",
        "currency": "UGX Sh",
        "id": 228
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Ukraine",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "UA",
        "iso3Code": "UKR",
        "timeZone": "Europe/Zaporozhye",
        "currency": "UAH ₴",
        "id": 229
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "United Arab Emirates",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "AE",
        "iso3Code": "ARE",
        "timeZone": "Asia/Dubai",
        "currency": "AED فلس",
        "id": 230
    },
    {
        "countryGeonameId": 6290252,
        "countryName": "United Kingdom",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "GB",
        "iso3Code": "GBR",
        "timeZone": "Europe/London",
        "currency": "GBP £",
        "id": 231
    },
    {
        "countryGeonameId": 7626844,
        "countryName": "United States",
        "continentName": "North America",
        "localeCode": "en",
        "continentCode": "NA",
        "isoCode": "US",
        "iso3Code": "USA",
        "timeZone": "Pacific/Honolulu",
        "currency": "USD $",
        "id": 232
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Uruguay",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "UY",
        "iso3Code": "URY",
        "timeZone": "America/Montevideo",
        "currency": "UYU $",
        "id": 233
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Uzbekistan",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "UZ",
        "iso3Code": "UZB",
        "timeZone": "Asia/Tashkent",
        "currency": "UZS soʻm",
        "id": 234
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Vanuatu",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "VU",
        "iso3Code": "VUT",
        "timeZone": "Pacific/Efate",
        "currency": "VUV Vt",
        "id": 235
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Vatican City",
        "continentName": "Europe",
        "localeCode": "en",
        "continentCode": "EU",
        "isoCode": "VA",
        "iso3Code": "VAT",
        "timeZone": "Europe/Vatican",
        "currency": "EUR €",
        "id": 236
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Venezuela",
        "continentName": "South America",
        "localeCode": "en",
        "continentCode": "SA",
        "isoCode": "VE",
        "iso3Code": "VEN",
        "timeZone": "America/Caracas",
        "currency": "VEF Bs",
        "id": 237
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Vietnam",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "VN",
        "iso3Code": "VNM",
        "timeZone": "Asia/Ho_Chi_Minh",
        "currency": "VND ₫",
        "id": 238
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Wallis and Futuna",
        "continentName": "Oceania",
        "localeCode": "en",
        "continentCode": "OC",
        "isoCode": "WF",
        "iso3Code": "WLF",
        "timeZone": "Pacific/Wallis",
        "currency": "CFP Fr",
        "id": 239
    },
    {
        "countryGeonameId": 2635167,
        "countryName": "Western Sahara",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "EH",
        "iso3Code": "ESH",
        "timeZone": "Africa/El_Aaiun",
        "currency": "MAD DH",
        "id": 240
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Yemen",
        "continentName": "Asia",
        "localeCode": "en",
        "continentCode": "AS",
        "isoCode": "YE",
        "iso3Code": "YEM",
        "timeZone": "Asia/Aden",
        "currency": " YER ﷼",
        "id": 241
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Zambia",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "ZM",
        "iso3Code": "ZMB",
        "timeZone": "Africa/Lusaka",
        "currency": "ZMW ZK",
        "id": 242
    },
    {
        "countryGeonameId": 6252001,
        "countryName": "Zimbabwe",
        "continentName": "Africa",
        "localeCode": "en",
        "continentCode": "AF",
        "isoCode": "ZW",
        "iso3Code": "ZWE",
        "timeZone": "Africa/Harare",
        "currency": "ZWD $",
        "id": 243
    }
]